dist: xenial

#addons:
#    packages:
#      - openssl@1.1

matrix:
  include:
    - rvm: 2.4.5
    - rvm: 2.5.5
    - rvm: 2.6.2
    - rvm: 2.4.5
      os: osx
    - rvm: 2.5.5
      os: osx
      osx_image: xcode10.1
      addons:
        packages:
          - openssl@1.1
    - rvm: 2.6.2
      os: osx
      osx_image: xcode10.1
      addons:
        packages:
          - openssl@1.1

script:
  - ruby -ropenssl -e "puts OpenSSL::OPENSSL_LIBRARY_VERSION, OpenSSL::OPENSSL_VERSION"
