dist: xenial

git:
  depth: 3

matrix:
  include:
    - rvm: 2.4.5
      a: x_10.1
      os: osx
      osx_image: xcode10.1
    - rvm: 2.5.5
      a: x_10.1
      os: osx
      osx_image: xcode10.1
    - rvm: 2.6.2
      a: x_10.1
      os: osx
      osx_image: xcode10.1
    - rvm: 2.4.5
      a: x_10.1_ssl
      os: osx
      osx_image: xcode10.1
      addons:
        packages:
          - openssl@1.1
    - rvm: 2.5.5
      a: x_10.1_ssl
      os: osx
      osx_image: xcode10.1
      addons:
        packages:
          - openssl@1.1
    - rvm: 2.6.2
      a: x_10.1_ssl
      os: osx
      osx_image: xcode10.1
      addons:
        packages:
          - openssl@1.1

script:
  - ruby openssl_info.rb
