# sudo: false

os:
  - linux

script:
  - "rvm use 2.0"
  - "ruby travis_info.rb"
  - "rvm use 2.1"
  - "ruby travis_info.rb"
  - "rvm use 2.2"
  - "ruby travis_info.rb"
  - "rvm use 2.3"
  - "ruby travis_info.rb"
  - "rvm use 2.4"
  - "ruby travis_info.rb"
  - "rvm use ruby-head"
  - "ruby travis_info.rb"

