dist: xenial

git:
  depth: 3

matrix:
  include:
    - rvm: 2.4.5
      os: osx
    - rvm: 2.5.5
      os: osx
    - rvm: 2.6.2
      os: osx
    - rvm: 2.4.5
      os: osx
      addons:
        packages:
          - openssl@1.1
    - rvm: 2.5.5
      os: osx
      addons:
        packages:
          - openssl@1.1
    - rvm: 2.6.2
      os: osx
      addons:
        packages:
          - openssl@1.1

script:
  - ruby openssl_info.rb
