# sudo: false

language: ruby
dist: trusty
sudo: required
rvm:
  - 2.2
  - 2.2.10
  - 2.3
  - 2.5
  - ruby-head

script:
  - gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)
  - gem update bundler --conservative
  - ruby -v
  - gem --version
  - bundle version
