dist: xenial

git:
  depth: 3

osx_image: xcode10.1

matrix:
  include:
    - rvm: 2.4.5
      os: osx
    - rvm: 2.5.5
      os: osx
    - rvm: 2.6.2
      os: osx

before_install:
  # rubygems 2.7.8 and greater include bundler, leave 2.6.0 untouched
  - |
    r_eng="$(ruby -e 'STDOUT.write RUBY_ENGINE')";
    rv="$(ruby -e 'STDOUT.write RUBY_VERSION')";
    if [ "$r_eng" == "ruby" ]; then
      if [ "$rv" -ge "2.5" ]; then gem install openssl --no-document
      fi
    fi

script:
  - ruby openssl_info.rb
