#!/usr/bin/env ruby

case ARGV
when %w(before_script)
  if /trunk/ =~ RUBY_DESCRIPTION
    require 'fileutils'
    puts "RbConfig::CONFIG['sitelibdir'] #{RbConfig::CONFIG['sitelibdir']}"
    Dir.chdir(RbConfig::CONFIG['sitelibdir']) { |d|
#      FileUtils.rm_r 'rubygems'
#      puts "FileUtils.rm_r 'rubygems' done"
      FileUtils.rm %w( rubygems.rb ubygems.rb )
    }
  end
else
  abort "unknown args #{ARGV.inspect}"
end
