#!/usr/bin/env ruby

puts "RUNNING SCRIPT"

if /trunk/ =~ RUBY_DESCRIPTION
  require 'fileutils'
  Dir.chdir(RbConfig::CONFIG['sitelibdir']) { |d|
    FileUtils.rm_r 'rubygems'
    puts "FileUtils.rm_r 'rubygems' done"
    FileUtils.rm %w( rubygems.rb ubygems.rb )
  }
end
